# Generated by Django 2.2 on 2020-03-14 10:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker_site', '0007_auto_20200313_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracking',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
